### ISSUE TITLE
Problems running git commands for the first time

### ISSUE THREAD

**Issue by CharleneMao** [blaserlab/datascience.curriculum#2]
> usethis::use_readme_md(open = FALSE)
√ Writing 'README.md'
> usethis::use_git()
√ Initialising Git repo
There are 8 uncommitted files:
* '.gitignore'
* '.Rbuildignore'
* '.Rprofile'
* 'LICENSE.md'
* 'R/'
* 'rclass_example.Rproj'
* 'README.md'
* 'renv/'
Is it ok to commit them?

1: Yes
2: No
3: Absolutely not

Selection: 1
√ Adding files
√ Making a commit with message 'Initial commit'
Error in libgit2::git_signature_default : 
  config value 'user.name' was not found

**Comment by blaserlab** [comment]
You can either skip using git or you need to run the git setup commands.

- go to R/git_commands.R
- scroll to the bottom box labeled "commands to configure git"
- uncomment this line by removing the hashtags:  
```
# usethis::use_git_config(user.name = "YourName",                        
#                         user.email = "your@mail.com") 
```

- fill in your github username and email address and run that line
- then uncomment this line:
`# usethis::create_github_token()` and run it to set a github token (like a password).  Copy the token that is generated. 
- then uncomment this line:
`# blaseRtemplates::gitcreds_set()` and run it.  Paste in the token at the prompt and hit enter.

You should be all set next time you try to run git.

**Comment by d-a-v-i-d-wu** [comment]
usethis::use_github(private = TRUE)
There are uncommitted changes and we're about to create and push to a new GitHub repo
Do you want to proceed anyway?

1: Absolutely
2: No
3: No way

Selection: 1
Error: GitHub PAT must have one of these forms:
  * 40 hexadecimal digits (older PATs)
  * A 'ghp_' prefix followed by 36 to 251 more characters (newer PATs)
Type .Last.error.trace to see where the error occurred

**Comment by ghost** [comment]
[ master ] > # initialize github
[ master ] > usethis::use_github(private = TRUE)
There are uncommitted changes and we're about to create and push to a new GitHub repo
Do you want to proceed anyway?

1: Yes
2: No
3: Not now

Selection: 1
√ Creating private GitHub repository 'Janek-Walker/workshop_project'
Error in gh_process_response(raw) : 
GitHub API error (404): 
Message: Not Found
Read more at https://docs.github.com/rest/reference/repos#create-a-repository-for-the-authenticated-user

URL not found: https://api.github.com/user/repos
Type .Last.error.trace to see where the error occurred

**Comment by blaserlab** [comment]
@d-a-v-i-d-wu, @Janek-Walker :  Did you run the commands to set up git and github?  These are on the bottom of git_commands.R.  

- run blaseRtemplates::regenerate_git_commands() to get the script back into your project if it isn't there
- scroll to the bottom.  Make sure your username and email match what you are using to access github.  Run:
```
usethis::use_git_config(user.name = "YourName",                         
                        user.email = "your@mail.com")                   
```

Then run:  

`usethis::create_github_token()`

Scroll to the bottom, click the green box.  It takes you to a new page which should look like this:

![image](https://user-images.githubusercontent.com/62366303/161455769-fc67e8b6-d54d-4e58-a3a2-8b75667cc2e2.png)

Copy the whole token by clicking on the blue squares.

Then run:

 `blaseRtemplates::gitcreds_set() ` and paste in your token.

@Janek-Walker it looks like you may have a mismatch in username or email.  I would check that first.
@d-a-v-i-d-wu it looks like you may have an incorrect token.  I would just try to repeat these steps to reset it. 

Let me know if these don't work.

**Comment by d-a-v-i-d-wu** [comment]
Thanks for the reply, I found I missed two letters when I copie the token , and now it works!


    On Sunday, April 3, 2022, 08:31:39 PM EDT, Brad Blaser ***@***.***> wrote:  
 
 


@d-a-v-i-d-wu, @Janek-Walker : Did you run the commands to set up git and github? These are on the bottom of git_commands.R.
   
   - run blaseRtemplates::regenerate_git_commands() to get the script back into your project if it isn't there
   - scroll to the bottom. Make sure your username and email match what you are using to access github. Run:
usethis::use_git_config(user.name = "YourName",                         
                        user.email = ***@***.***")                   

Then run:

usethis::create_github_token()

Scroll to the bottom, click the green box. It takes you to a new page which should look like this:



Copy the whole token by clicking on the blue squares.

Then run:

blaseRtemplates::gitcreds_set()  and paste in your token.

@Janek-Walker it looks like you may have a mismatch in username or email. I would check that first.
@d-a-v-i-d-wu it looks like you may have an incorrect token. I would just try to repeat these steps to reset it.

Let me know if these don't work.

**Comment by blaserlab** [comment]
We found out that you cannot have **internet explorer** set to be your default browser.  This will cause issues with github permissions.  Closing this issue.
