### ISSUE TITLE
Error installing 'blaseRtemplates'

### ISSUE THREAD

**Issue by kcollier130** [blaserlab/datascience.curriculum#3]
Error installing 'blaseRtemplates' despite latest version of R and RStudio

> renv::install("blaserlab/blaseRtemplates")
Retrieving 'https://api.github.com/repos/blaserlab/blaseRtemplates/tarball/22431320e2c1ab2f030c14075b8721d96068c789' ...
	OK [downloaded 19.6 Kb in 1.1 secs]
Installing prompt [1.0.1] ...
	OK [linked cache]
Installing drat [0.2.2] ...
	OK [linked cache]
Installing pkgbuild [1.3.1] ...
	OK [linked cache]
Installing pkgload [1.2.4] ...
	OK [linked cache]
Installing sessioninfo [1.2.2] ...
	OK [linked cache]
Installing xopen [1.0.0] ...
	OK [linked cache]
Installing rcmdcheck [1.4.0] ...
	OK [linked cache]
Installing remotes [2.4.2] ...
	OK [linked cache]
Installing brew [1.0-7] ...
	OK [linked cache]
Installing commonmark [1.8.0] ...
	OK [linked cache]
Installing roxygen2 [7.1.2] ...
	OK [linked cache]
Installing rversions [2.1.1] ...
	OK [linked cache]
Installing brio [1.1.3] ...
	OK [linked cache]
Installing praise [1.0.0] ...
	OK [linked cache]
Installing diffobj [0.3.5] ...
	OK [linked cache]
Installing waldo [0.4.0] ...
	OK [linked cache]
Installing testthat [3.1.3] ...
	OK [linked cache]
Installing devtools [2.4.3] ...
	OK [linked cache]
Installing pak [0.2.1] ...
	OK [linked cache]
Installing blaseRtemplates [0.0.0.9088] ...
	FAILED
Error installing package 'blaseRtemplates':
===========================================

installing *source* package 'blaseRtemplates' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/katha/AppData/Local/Temp/RtmpSOimFS/renv-package-new-7a4c45c44d84/blaseRtemplates/R/bb_renv_datapkg.R:28:72: unexpected '>'
27:       } else {
28:         latest_version <- file.info(list.files(path, full.names = T)) |>
_______________________________________________________________^
ERROR: unable to collate and parse R files for package 'blaseRtemplates'
removing 'C:/Users/katha/R_Workshop/renv/staging/5/blaseRtemplates'
Error: install of package 'blaseRtemplates' failed [error code 1]

**Comment by blaserlab** [comment]
Looks like you need to update your version of R to 4.1 or greater.

Check out this link for how to do update R:  https://jennhuck.github.io/workshops/install_update_R.html.  

Then try to reinstall.  Let me know if it doesn't work.

**Comment by blaserlab** [comment]
Marking this closed.  Feel free to open another issue if you are still having problems.
