### ISSUE TITLE
  could not find function "conflict_prefer" 

### ISSUE THREAD

**Issue by d-a-v-i-d-wu** [blaserlab/datascience.curriculum#5]
[ master ] > conflict_prefer("filter", "dplyr")
Error in conflict_prefer("filter", "dplyr") : 
  could not find function "conflict_prefer"

**Comment by blaserlab** [comment]
Start by sourcing "R/dependencies.R".  That will attach the "conflicted" package.

Conflicted identifies conflicting function names in the packages you attach using the "library" command.  It prevents you from using those functions until you declare a preference using `conflic_prefer()`.  This is a safeguard to prevent unrecognized and difficult to interpret errors down the road.

Always source "R/dependencies.R" first and then "R/configs.R" before you work on your project.

**Comment by d-a-v-i-d-wu** [comment]
Thanks!
